[project]
name = "server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dynaconf>=3.2.11",
    "email-validator>=2.3.0",
    "fastapi[standard]>=0.117.1",
    "psycopg2-binary>=2.9.10",
    "sqlmodel>=0.0.25",
]
